name: WLED-MM compile (ESP32-C3, v14.5.0-beta)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio --version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch MoonModules/WLED-MM v14.5.0-beta
        run: |
          set -euxo pipefail
          rm -rf /tmp/WLEDtemp || true
          mkdir -p /tmp/WLEDtemp
          wget "https://api.github.com/repos/MoonModules/WLED/zipball/v14.5.0-beta" -O /tmp/WLEDtemp/wledmm.zip
          unzip /tmp/WLEDtemp/wledmm.zip -d /tmp/WLEDtemp
          find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -type d | head -n1 > /tmp/WLEDtemp/wledfoldername
          echo "WLED-MM dir: $(cat /tmp/WLEDtemp/wledfoldername)"

      - name: Build (PlatformIO)
        run: |
          set -euxo pipefail
          WLED_DIR="$(cat /tmp/WLEDtemp/wledfoldername)"
          cd "$WLED_DIR"

          # Build Web UI
          npm ci
          npm run build

          # Custom environment for ESP32-C3
          {
            echo ''
            echo '[env:custom_build]'
            echo 'extends = env:esp32c3dev'
            # Wymuszenie trybu flash DIO i partycji 4MB (dla C3 to zwykle właściwe)
            echo 'board_build.flash_mode = dio'
            echo 'board_build.partitions = tools/WLED/partitions/esp32_partition_app4M.csv'
          } >> platformio.ini

          echo "==== platformio.ini (tail) ===="
          tail -n 20 platformio.ini

          # Build firmware
          pio run -e custom_build -v

      - name: Copy firmware set + scripts into repo
        run: |
          set -euxo pipefail
          cd "$GITHUB_WORKSPACE"

          # ensure previous files removed to force fresh commit
          git rm -f bootloader.bin partitions.bin custom_build.bin flash.sh flash.bat checksums.txt || true

          WLED_DIR="$(cat /tmp/WLEDtemp/wledfoldername)"

          # Copy firmware
          install -m 0644 "${WLED_DIR}/build_output/firmware/custom_build.bin" .
          install -m 0644 "${WLED_DIR}/.pio/build/custom_build/bootloader.bin" .
          install -m 0644 "${WLED_DIR}/.pio/build/custom_build/partitions.bin" .

          # flash.sh (Linux/macOS)
          cat > flash.sh <<'BASH'
          #!/bin/bash
          set -e
          PORT=${1:-/dev/ttyUSB0}
          BAUD=${2:-460800}

          esptool.py --chip esp32c3 --port "$PORT" --baud "$BAUD" write_flash --encrypt \
            0x0     bootloader.bin \
            0x8000  partitions.bin \
            0x10000 custom_build.bin
          BASH
          chmod +x flash.sh

          # flash.bat (Windows)
          cat > flash.bat <<'BAT'
          @echo off
          set PORT=%1
          if "%PORT%"=="" set PORT=COM3
          set BAUD=%2
          if "%BAUD%"=="" set BAUD=460800

          esptool.py --chip esp32c3 --port %PORT% --baud %BAUD% write_flash --encrypt ^
            0x0     bootloader.bin ^
            0x8000  partitions.bin ^
            0x10000 custom_build.bin
          BAT

          # checksums
          sha256sum bootloader.bin partitions.bin custom_build.bin > checksums.txt

          date -I > last_update_date.txt

      - name: Upload artifacts (firmware + scripts)
        uses: actions/upload-artifact@v4
        with:
          name: wled_mm_esp32c3_v14.5.0-beta
          path: |
            custom_build.bin
            bootloader.bin
            partitions.bin
            flash.sh
            flash.bat
            checksums.txt
            last_update_date.txt
          if-no-files-found: error

      - name: Commit files
        run: |
          set -euxo pipefail
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -A
          git commit -m "WLED-MM v14.5.0-beta (ESP32-C3) – app+bootloader+partitions+scripts (DIO + 4MB)" || echo "No changes"
          git push origin HEAD:main
