name: WLED-MM compile (ESP32-C3, v14.5.0-beta)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio --version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch MoonModules/WLED-MM v14.5.0-beta
        run: |
          set -euxo pipefail
          rm -rf /tmp/WLEDtemp || true
          mkdir -p /tmp/WLEDtemp
          wget "https://api.github.com/repos/MoonModules/WLED/zipball/v14.5.0-beta" -O /tmp/WLEDtemp/wledmm.zip
          unzip /tmp/WLEDtemp/wledmm.zip -d /tmp/WLEDtemp
          find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -type d | head -n1 > /tmp/WLEDtemp/wledfoldername
          echo "WLED-MM dir: $(cat /tmp/WLEDtemp/wledfoldername)"

      - name: Build (PlatformIO)
        run: |
          set -euxo pipefail
          WLED_DIR="$(cat /tmp/WLEDtemp/wledfoldername)"
          cd "$WLED_DIR"

          # Zbuduj Web UI
          npm ci
          npm run build

          # Dodaj środowisko tylko z esp32c3dev
          {
            echo ''
            echo '[env:custom_build]'
            echo 'extends = env:esp32c3dev'
          } >> platformio.ini

          echo "==== platformio.ini (tail) ===="
          tail -n 20 platformio.ini

          # Kompilacja
          pio run -e custom_build -v

      - name: Copy firmware set into repo
        run: |
          set -euxo pipefail
          cd "$GITHUB_WORKSPACE"
          git rm -r *.bin || true
          WLED_DIR="$(cat /tmp/WLEDtemp/wledfoldername)"
          # app:
          cp "${WLED_DIR}/build_output/firmware/custom_build.bin" "$GITHUB_WORKSPACE/"
          # bootloader + partitions z tego samego builda:
          cp "${WLED_DIR}/.pio/build/custom_build/bootloader.bin" "$GITHUB_WORKSPACE/"
          cp "${WLED_DIR}/.pio/build/custom_build/partitions.bin" "$GITHUB_WORKSPACE/"
          date -I > "$GITHUB_WORKSPACE/last_update_date.txt"

      - name: Upload artifacts (firmware set)
        uses: actions/upload-artifact@v4
        with:
          name: wled_mm_esp32c3_v14.5.0-beta
          path: |
            custom_build.bin
            bootloader.bin
            partitions.bin
          if-no-files-found: error

      - name: Commit files
        run: |
          set -euxo pipefail
          cd "$GITHUB_WORKSPACE"
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add custom_build.bin bootloader.bin partitions.bin last_update_date.txt
          git commit -m "WLED-MM v14.5.0-beta (ESP32-C3) – app+bootloader+partitions" || echo "No changes"
          git push origin HEAD:main
