name: WLED compile (ESP32-C3 + AudioReactive)

on:
  workflow_dispatch:
    inputs:
      wled_tag:
        description: 'WLED release tag (np. v0.15.0)'
        required: false
        default: 'v0.15.0'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WLED_TAG: ${{ inputs.wled_tag || 'v0.15.0' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio --version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch WLED ${{ env.WLED_TAG }}
        run: |
          set -euo pipefail
          rm -rf /tmp/WLEDtemp || true
          mkdir -p /tmp/WLEDtemp
          wget "https://api.github.com/repos/Aircoookie/WLED/zipball/${WLED_TAG}" -O /tmp/WLEDtemp/wled.zip
          unzip /tmp/WLEDtemp/wled.zip -d /tmp/WLEDtemp
          # zapisz dokładnie 1 ścieżkę do rozpakowanego folderu
          find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -type d | head -n1 > /tmp/WLEDtemp/wledfoldername
          echo "WLED dir: $(cat /tmp/WLEDtemp/wledfoldername)"

      - name: Build (PlatformIO)
        run: |
          set -euo pipefail
          WLED_DIR="$(cat /tmp/WLEDtemp/wledfoldername)"
          cd "$WLED_DIR"

          # Zbuduj frontend (ważne, inaczej GUI może nie widzieć usermodów)
          npm ci
          npm run build

          # Dodaj środowisko z AudioReactive i Twoimi pinami
          cat >> platformio.ini << 'EOF'

[env:custom_build]
extends = env:esp32c3dev
custom_usermods = audioreactive
build_flags = ${env:esp32c3dev.build_flags} -D UM_AUDIOREACTIVE_ENABLE -D SR_DMTYPE=1 -D BTNPIN=8 -D LEDPIN=19 -D I2S_SDPIN=3 -D I2S_WSPIN=4 -D I2S_CKPIN=5 -D ARDUINO_USB_CDC_ON_BOOT=0
build_unflags = -D WLED_RELEASE_NAME
# (opcjonalnie, dla 4MB) odkomentuj:
# board_build.partitions = default_4MB.csv
EOF

          # Kompilacja
          pio run -e custom_build

      - name: Copy Files into repo
        run: |
          set -euo pipefail
          cd "$GITHUB_WORKSPACE"
          git rm -r *.bin || true
          WLED_DIR="$(cat /tmp/WLEDtemp/wledfoldername)"
          cp "${WLED_DIR}/build_output/firmware/custom_build.bin" "$GITHUB_WORKSPACE/"
          date -I | tr -d '\n' > "$GITHUB_WORKSPACE/last_update_date.txt"

      - name: Upload artifact (custom_build.bin)
        uses: actions/upload-artifact@v4
        with:
          name: custom_build
          path: custom_build.bin
          if-no-files-found: error

      - name: Commit Files
        run: |
          set -euo pipefail
          cd "$GITHUB_WORKSPACE"
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add custom_build.bin last_update_date.txt
          git commit -m "Commit Custom Build (${WLED_TAG})" || echo "No changes to commit"
          git push origin HEAD:main
