name: WLED compile (ESP32-C3 + AudioReactive)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Set up Node.js (build Web UI)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Pobierz czyste WLED 0.15.0 (możesz zmienić na nowszy tag)
      - name: Fetch WLED
        env:
          WLED_TAG: v0.15.0
        run: |
          rm -rf /tmp/WLEDtemp || true
          mkdir -p /tmp/WLEDtemp
          wget "https://api.github.com/repos/Aircoookie/WLED/zipball/${WLED_TAG}" -O /tmp/WLEDtemp/wled.zip
          unzip /tmp/WLEDtemp/wled.zip -d /tmp/WLEDtemp
          find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -type d > /tmp/WLEDtemp/wledfoldername

      - name: Build (PlatformIO)
        run: |
          cd "$(cat /tmp/WLEDtemp/wledfoldername)"

          # Zbuduj frontend, żeby web UI znalazło się w binarce
          npm ci
          npm run build

          # Dodaj środowisko kompilacji dla ESP32-C3 z AudioReactive
          {
            echo ''
            echo '[env:custom_build]'
            echo 'extends = env:esp32c3dev'
            echo 'build_flags = ${env:esp32c3dev.build_flags} -D USERMOD_AUDIOREACTIVE -D BTNPIN=8 -D ARDUINO_USB_CDC_ON_BOOT=0'
            echo 'build_unflags = -D WLED_RELEASE_NAME'
            # (opcjonalnie) wymuś tablice partycji 4MB:
            # echo 'board_build.partitions = default_4MB.csv'
          } >> platformio.ini

          # Kompilacja
          pio run -e custom_build || pio run -e custom_build

      - name: Copy Files
        run: |
          cd "$GITHUB_WORKSPACE"
          git rm -r *.bin || true
          WLEDFOLDERNAME="$(cat /tmp/WLEDtemp/wledfoldername)"
          cp "${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin" "$GITHUB_WORKSPACE/"
          date -I | tr -d '\n' > "$GITHUB_WORKSPACE/last_update_date.txt"

      - name: Commit Files
        run: |
          cd "$GITHUB_WORKSPACE"
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add custom_build.bin last_update_date.txt
          git commit -m "Commit Custom Build" || echo "Nothing to commit"
          git push origin HEAD:main
